#!/bin/bash
#
# composer-foreach  --  a 'git submodule foreach' replacement for Composer
# 
# Copyright (c) 2014  Josef Kufner <jk@frozen-doe.net>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

# colors
NOCOLOR="\033[;0m"
BLACK="\033[0;30m"
BLUE="\033[0;34m"
GREEN="\033[0;32m"
CYAN="\033[0;36m"
RED="\033[0;31m"
PURPLE="\033[0;35m"
BROWN="\033[0;33m"
GRAY="\033[0;37m"
# light colors
LBLACK="\033[1;30m"
LBLUE="\033[1;34m"
LGREEN="\033[1;32m"
LCYAN="\033[1;36m"
LRED="\033[1;31m"
LPURPLE="\033[1;35m"
LBROWN="\033[1;33m"
LGRAY="\033[1;37m"

composer show -iP | sed 's/^\([^ ]\+\) \+/\1\n/' | while IFS=$'\n' read -r pkg && IFS=$'\n' read -r dir
do

	# make sure this is a git repo
	if ! [ -d  "$dir/.git" ]
	then
		continue
	fi

	# ignore repo with detached heads
	s=$(cd "$dir" && git status --porcelain -b)
	if [ "$?" != 0 ] || [ "$s" == "## HEAD (no branch)" ]
	then
		continue
	fi

	# make sure we are in git repo root -- if this is not git repo with composer package, this will fail
	if [ $(cd "$dir" && git ls-tree --full-name --name-only HEAD composer.json) != "composer.json" ]
	then
		continue
	fi

	# ok, run the command
	echo -e "\n${CYAN}Processing package ${LCYAN}$pkg${CYAN} in \"$dir\" ...${NOCOLOR}\n"
	( cd "$dir" && $@ )
	echo

done

